const programming = [
    { id: 1, name: "Pro_Html" },
    { id: 2, name: "Pro_Css" },
    { id: 3, name: "Pro_Css3" },
    { id: 4, name: "Pro_H5" },
    { id: 5, name: "Pro_SVG" },
    { id: 6, name: "Pro_Frame" },
    { id: 7, name: "Pro_Mobile" },
    { id: 8, name: "Pro_Responsive" },
    { id: 9, name: "Pro_Javascript" },
    { id: 10, name: "Pro_ES6 - 11" },
    { id: 11, name: "Pro_jQuery" },
    { id: 12, name: "Pro_Vue.js" },
    { id: 13, name: "Pro_Vue2.js" },
    { id: 14, name: "Pro_Uni-app" },
    { id: 15, name: "Pro_Java" },
    { id: 16, name: "Pro_ Ajax" },
    { id: 17, name: "Pro_RegExp" },
    { id: 18, name: "Pro_Xiaochengxu" },
    { id: 19, name: "Pro_ Python" },
    { id: 20, name: "Pro_Mysql" },
    { id: 21, name: "Pro_Houdunren" },
    { id: 22, name: "Pro_Less and Sass" },
    { id: 23, name: "Pro_Standard" },
    { id: 24, name: "Pro_Code effect" },
    { id: 25, name: "Pro_Webpack" },
    { id: 26, name: "Pro_ChatGPT" },
];
const studyOther = [
    { id: 1, name: "O_Video" },
    { id: 2, name: "O_VIPN" },
    { id: 3, name: "O_English" },
    { id: 4, name: "O_Excel Word" },
    { id: 5, name: "O_Homebrew" },
    { id: 6, name: "O_Unit conversion" },
    { id: 7, name: "O_Visual Studio Code" },
    { id: 8, name: "O_MarkDown" },
    { id: 9, name: "O_Iterm2" },
];
const working = [
    { id: 1, name: "Wor_Xhy" },
    { id: 2, name: "Wor_Data" },
    { id: 3, name: "Wor_1010" },
    { id: 4, name: "Wor_Other" },
    { id: 5, name: "Wor_Yunxi" },
    { id: 6, name: "Wor_Aerfa" },
    { id: 7, name: "Wor_Haixun" },
    { id: 8, name: "Wor_Tiangong" },
    { id: 9, name: "Wor_Touneng" },
    { id: 10, name: "Wor_Yuncheng" },
    { id: 11, name: "Wor_Yxmengban" },
];
const sourceMaterial = [
    { id: 1, name: "Link_PPT" },
    { id: 2, name: "Link_Tool" },
    { id: 3, name: "Link_Color" },
    { id: 4, name: "Link_Other" },
    { id: 5, name: "Link_Videos" },
    { id: 6, name: "Link_Images" },
    { id: 7, name: "Link_Template" },
    { id: 8, name: "Link_Software" },
    { id: 9, name: "Link_Programming" },
    { id: 10, name: "Link_Plug in" },
];
const softwareList = [
    { id: 1, name: "Pro_IDM" },
    { id: 2, name: "Pro_CDR" },
    { id: 3, name: "Pro_PPT" },
    { id: 4, name: "Pro_PDF" },
    { id: 5, name: "Pro_CAD" },
    { id: 6, name: "Pro_WPS" },
    { id: 7, name: "Pro_Fxcp" },
    { id: 8, name: "Pro_Xmind" },
    { id: 9, name: "Pro_Office" },
    { id: 10, name: "Pro_Topaz" },
    { id: 11, name: "Pro_Google" },
    { id: 12, name: "Pro_3D map" },
    { id: 13, name: "Pro_Arctime" },
    { id: 77, name: "Pro_Blender" },
    { id: 14, name: "Pro_3ds max" },
    { id: 15, name: "Pro_Potplays" },
    { id: 16, name: "Pro_DaVinci" },
    { id: 17, name: "Pro_Easy CHM" },
    { id: 18, name: "Pro_image.png" },
    { id: 19, name: "Pro_Word study" },
    { id: 20, name: "Pro_Android apk" },
    { id: 21, name: "Pro_Programming" },
    { id: 22, name: "Pro_AnyDesk v5.10" },
    { id: 23, name: "Pro_精雕" },
    { id: 24, name: "Pro_录屏" },
    { id: 25, name: "Pro_拼图" },
    { id: 26, name: "Pro_西游2" },
    { id: 27, name: "Pro_音乐" },
    { id: 28, name: "Pro_AI修图" },
    { id: 29, name: "Pro_火萤酱" },
    { id: 30, name: "Pro_USB共享" },
    { id: 31, name: "Pro_冰点文库" },
    { id: 32, name: "Pro_模拟器" },
    { id: 33, name: "Pro_视频加密" },
    { id: 34, name: "Pro_亿图图示" },
    { id: 35, name: "Pro_亿图图库" },
    { id: 36, name: "Pro_影藏工具" },
    { id: 37, name: "Pro_音乐软件" },
    { id: 38, name: "Pro_测量工具" },
    { id: 39, name: "Pro_动态桌面" },
    { id: 40, name: "Pro_查看流量" },
    { id: 41, name: "Pro_金盾2016" },
    { id: 42, name: "Pro_仿色软件" },
    { id: 43, name: "Pro_封装软件" },
    { id: 44, name: "Pro_硬盘哨兵" },
    { id: 45, name: "Pro_图片压缩" },
    { id: 46, name: "Pro_人像磨皮" },
    { id: 47, name: "Pro_数据擦除" },
    { id: 48, name: "Pro_云盘搜索" },
    { id: 49, name: "Pro_文件加密夹" },
    { id: 50, name: "Pro_图片转矢量" },
    { id: 51, name: "Pro_酒格计算器" },
    { id: 52, name: "Pro_资源查看器" },
    { id: 53, name: "Pro_语音转文字" },
    { id: 54, name: "Pro_文字识别器" },
    { id: 55, name: "Pro_图灵机器人" },
    { id: 56, name: "Pro_字幕FastTitle" },
    { id: 57, name: "Pro_硬盘分区助手" },
    { id: 58, name: "Pro_获取程序权限" },
    { id: 59, name: "Pro_黑白图片上色" },
    { id: 60, name: "Pro_Ps缩略图查看" },
    { id: 61, name: "Pro_清理重复文件" },
    { id: 62, name: "Pro_图片无损放大" },
    { id: 63, name: "Pro_流行网络电视" },
    { id: 64, name: "Pro_IE兼容性测试" },
    { id: 65, name: "Pro_西部数码固态" },
    { id: 66, name: "Pro_机器仿真工具" },
    { id: 67, name: "Pro_CHM编辑软件" },
    { id: 68, name: "Pro_鼠标右键扩展" },
    { id: 74, name: "Pro_动态图片制作" },
    { id: 69, name: "Pro_GIF录像生成器" },
    { id: 70, name: "Pro_人声音频分离器" },
    { id: 71, name: "Pro_修改文字协注册" },
    { id: 72, name: "Pro_查看资源被占用" },
    { id: 73, name: "Pro_硬盘文件加密夹" },
];
const adobeList = [
    { id: 1, name: "Adobe_Ae" },
    { id: 2, name: "Adobe_Au" },
    { id: 3, name: "Adobe_Ai" },
    { id: 4, name: "Adobe_Br" },
    { id: 6, name: "Adobe_Dw" },
    { id: 7, name: "Adobe_Fw" },
    { id: 8, name: "Adobe_Lr" },
    { id: 9, name: "Adobe_Me" },
];
const systemList = [
    { id: 1, name: "C_MacOS" },
    { id: 2, name: "C_PlugIn" },
    { id: 3, name: "C_Windows" },
];
const github = [
    { id: 1, name: "G_github" },
    { id: 2, name: "G_git/gitee" },
];
const subTitleList = [
    { id: 1, name: "S_创造营" },
    { id: 2, name: "S_新游记" },
    { id: 3, name: "S_明日之子" },
    { id: 4, name: "S_半熟恋人" },
    { id: 6, name: "S_为歌而赞" },
    { id: 7, name: "S_恋恋剧中人" },
    { id: 8, name: "S_哥哥的滚烫人生" },
];
const lifeList = [
    { id: 1, name: "L_Food" },
    { id: 2, name: "L_Game" },
    { id: 3, name: "L_Wedding" },
    { id: 4, name: "L_Question" },
    { id: 6, name: "L_Language" },
];
const storage = [{ id: 1, name: "T_text" }];

export { programming, github, studyOther, working, sourceMaterial, softwareList, adobeList, systemList, subTitleList, lifeList, storage };
