const menuDate = [
    { id: 1, name: "Pro_Html" },
    { id: 2, name: "Pro_Css" },
    { id: 3, name: "Pro_Css3" },
    { id: 4, name: "Pro_H5" },
    { id: 5, name: "Pro_SVG" },
    { id: 6, name: "Pro_Frame" },
    { id: 7, name: "Pro_Mobile" },
    { id: 8, name: "Pro_Responsive" },
    { id: 9, name: "Pro_Javascript" },
    { id: 10, name: "Pro_ES6 - 11" },
    { id: 11, name: "Pro_jQuery" },
    { id: 12, name: "Pro_Vue.js" },
    { id: 13, name: "Pro_Vue2.js" },
    { id: 14, name: "Pro_Uni-app" },
    { id: 15, name: "Pro_Java" },
    { id: 16, name: "Pro_ Ajax" },
    { id: 17, name: "Pro_RegExp" },
    { id: 18, name: "Pro_Xiaochengxu" },
    { id: 19, name: "Pro_ Python" },
    { id: 20, name: "Pro_Mysql" },
    { id: 21, name: "Pro_Houdunren" },
    { id: 22, name: "Pro_Less and Sass" },
    { id: 23, name: "Pro_Standard" },
    { id: 24, name: "Pro_Code effect" },
    { id: 25, name: "Pro_Webpack" },
    { id: 26, name: "Pro_ChatGPT" },
];

const studyOther  = [
    {id:1,name:"O_Video"},
    {id:2,name:"O_VIPN"},
    {id:3,name:"O_English"},
    {id:4,name:"O_Excel Word"},
    {id:5,name:"O_Homebrew"},
    {id:6,name:"O_Unit conversion"},
    {id:7,name:"O_Visual Studio Code"},
    {id:8,name:"O_MarkDown"},
    {id:9,name:"O_Iterm2"},
]

export {menuDate,studyOther};
